[package]
name = "starknet-privacy-mixer"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = ">=2.4.0"

[[target.starknet-contract]]
sierra = true
casm = true

[tool.snfoundry]
account = "account"
accounts-file = "~/.starknet_accounts/starknet_open_zeppelin_accounts.json"
network = "alpha-goerli"
url = "https://alpha4.starknet.io"
